# Label Encoder

In [ ]:
# import pandas as pd
# from sklearn.preprocessing import LabelEncoder
# obj = LabelEncoder()
# df["colname"] = obj.fit_transform(df["col_name"])

In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
LE = LabelEncoder()
df = pd.DataFrame({"Gender": ["Male","Female","Male","Male","Others","Female","Male"]})
df["Gender"] = LE.fit_transform(df["Gender"])
df

   Gender
0       1
1       0
2       1
3       1
4       2
5       0
6       1

# OneHotEncoder

In [ ]:
# from sklearn.preprocessing import OneHotEncoder
# obj = OneHotEncoder(sparse_output = False)
# data = obj.fit_transform(df[[col_name]])
# names =  obj.get_feature_names_out([col_name])
# df = pd.DataFrame(data,columns = names)

In [ ]:
from sklearn.preprocessing import OneHotEncoder
OHE = OneHotEncoder(sparse_output=False)
df1 = pd.DataFrame({"Product": ["Laptop","Mobile","AC","Laptop","AC","Washing Machine","Mobile"]})
df1
data = OHE.fit_transform(df1[["Product"]])
names = OHE.get_feature_names_out(["Product"])
df = pd.DataFrame(data,columns = names)
df

   Product_AC  Product_Laptop  Product_Mobile  Product_Washing Machine
0         0.0             1.0             0.0                      0.0
1         0.0             0.0             1.0                      0.0
2         1.0             0.0             0.0                      0.0
3         0.0             1.0             0.0                      0.0
4         1.0             0.0             0.0                      0.0
5         0.0             0.0             0.0                      1.0
6         0.0             0.0             1.0                      0.0

# OrdinalEncoder

In [ ]:
# from sklearn.preprocessing import OrdinalEncoder
# obj = OrdinalEncoder(categories=[["cat1","cat2","cat3",....,"catN"]])
# df[col_name] = obj.fit_transform(df[[col_name]])

In [ ]:
from ast import Or
from sklearn.preprocessing import OrdinalEncoder
df = pd.DataFrame({"Salary": ["Low","High","Medium","Low","Medium","Low","Low","High"]})
ORD = OrdinalEncoder(categories=[["Low","Medium","High"]])
df["Salary"] = ORD.fit_transform(df[["Salary"]])
df

   Salary
0     0.0
1     2.0
2     1.0
3     0.0
4     1.0
5     0.0
6     0.0
7     2.0