# Normalisation

In [ ]:
import pandas as pd
from sklearn.preprocessing import Normalizer
df = pd.DataFrame({"Weight": [75,85,45,67,85,88,93,56,78,84],
                   "Height": [170,178,134,156,174,187,198,183,176,138]})
norm = Normalizer()
data = norm.fit_transform(df)
df=pd.DataFrame(data,columns=df.columns)
df

     Weight    Height
0  0.403640  0.914918
1  0.430917  0.902391
2  0.318349  0.947973
3  0.394630  0.918840
4  0.438932  0.898520
5  0.425797  0.904819
6  0.425136  0.905129
7  0.292617  0.956230
8  0.405174  0.914239
9  0.519947  0.854199

# StandardScaler

In [ ]:
from sklearn.preprocessing import StandardScaler
std = StandardScaler()
df = pd.DataFrame({"Weight": [75,85,45,67,85,88,93,56,78,84],
                   "Height": [170,178,134,156,174,187,198,183,176,138]})
data = std.fit_transform(df)
df = pd.DataFrame(data,columns=df.columns)
df

     Weight    Height
0 -0.041361  0.030498
1  0.647983  0.437140
2 -2.109392 -1.799390
3 -0.592836 -0.681125
4  0.647983  0.233819
5  0.854786  0.894612
6  1.199458  1.453745
7 -1.351114  0.691291
8  0.165443  0.335480
9  0.579049 -1.596069