# Gradient Boosting Regessor

In [ ]:
import pandas as pd
from sklearn.ensemble import GradientBoostingRegressor,GradientBoostingClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error,confusion_matrix,accuracy_score,f1_score

In [ ]:
df=pd.read_csv("/content/house_price_regression_dataset.csv")
df

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality,House_Price
0,1360,2,1,1981,0.599637,0,5,2.623829e+05
1,4272,3,3,2016,4.753014,1,6,9.852609e+05
2,3592,1,2,2016,3.634823,0,9,7.779774e+05
3,966,1,2,1977,2.730667,1,8,2.296989e+05
4,4926,2,1,1993,4.699073,0,8,1.041741e+06
...,...,...,...,...,...,...,...,...
995,3261,4,1,1978,2.165110,2,10,7.014940e+05
996,3179,1,2,1999,2.977123,1,10,6.837232e+05
997,2606,4,2,1962,4.055067,0,2,5.720240e+05
998,4723,5,2,1950,1.930921,0,7,9.648653e+05
999,3268,4,2,1983,3.108790,2,2,7.425993e+05

In [ ]:
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [ ]:
Xtrain,Xtest,ytrain,ytest=train_test_split(X,y,test_size=0.3,random_state=42)

In [ ]:
modelr=GradientBoostingRegressor(n_estimators=300)
modelr.fit(Xtrain,ytrain)

GradientBoostingRegressor(n_estimators=300)

In [ ]:
ypredr=modelr.predict(Xtest)
ypredr

array([ 857443.51702032,  500266.87450342,  937256.90483051,
       1042505.35630493,  776053.87783168,  724782.91568479,
        981506.02808348,  894783.19236935,  818271.42838118,
        939172.83616977,  744111.77290181,  640682.20590549,
        223934.08158028, 1034439.05557455,  546544.56064302,
        194737.04562167,  470100.01882584,  368690.31131342,
        741501.31727387,  363730.74933518,  771614.69974146,
        486548.73827507,  675321.01434847,  885948.98932233,
        445234.73033527,  394343.14797251,  450149.97676862,
        437815.07800683,  190988.53138885,  473179.21667809,
        265642.12793323,  910640.65807181,  777354.16793297,
        355544.29854035,  490419.98019657,  748974.74073904,
        463471.84959558,  570841.53259819,  282078.35183381,
        160171.23405588,  298297.12636589,  298941.2899555 ,
        495790.69884282,  314173.87368321, 1076874.4437408 ,
       1011619.21067542,  782278.83600196,  821518.19161675,
       1009966.64889344,  681573.91229467,  287081.25524758,
        748887.92265532,  819034.28669796,  709014.67978636,
        523386.53599494,  797967.43478101,  195746.5683062 ,
        329717.1657141 ,  714775.7661456 ,  235604.6124932 ,
        977945.00420545,  366532.22324162,  317810.94503568,
        500787.72701501,  589620.28549109,  558367.79153532,
        482797.20367926,  745126.94878718,  967696.88051134,
        727539.81303154,  465815.56374471,  838502.09318228,
        266886.15535855,  587487.52013683,  674430.54727433,
        739946.65146375,  546899.7953549 ,  208607.98849494,
        557844.61558623,  885896.13232386,  555197.76530322,
        418908.53731927,  535170.29468208,  206878.78927225,
        157229.25524794,  364025.19512512,  957059.89515036,
        926003.61840158,  538142.04723103,  238286.59960091,
        925302.58955085,  780586.01567222,  377837.85278077,
        803513.99343091,  704130.80014465, 1042433.68473124,
        770719.1561683 ,  893837.26534764,  852279.45720431,
        596286.68056536,  912319.27753812,  856365.5793438 ,
        282027.36461881,  619877.19436165,  458392.30522857,
        929629.82340119,  579269.10777997,  217684.21524538,
        273305.69613389, 1029571.61859705,  823575.52212362,
        402000.79063224,  906749.50465107,  554313.74270692,
        734235.0113957 ,  930554.65295388,  262752.85520447,
        874663.12051397,  239196.04413687,  736858.01458162,
        255779.36899546,  478114.2446888 ,  859453.69977334,
        242336.32261766,  338113.57310987,  309001.08701468,
        554365.04471662,  842819.34041353,  988621.71576903,
        584258.26281526,  787497.27845646,  687752.77235402,
        614822.11498846,  699419.83888498,  678697.51630781,
        867917.63017018,  515234.76015822,  622969.15068273,
        657816.16844193,  233570.66419896,  482128.56314229,
        843579.6318997 ,  347229.47117456,  737331.55610567,
        875702.12430213,  350528.89406672,  942293.22917147,
        360954.96698692,  700133.01184572,  939517.49846149,
        561731.71567557,  803420.95128172,  956397.93149304,
        911051.39511963, 1051041.82309631,  685775.10462112,
        261526.49933589,  635038.21911214,  977778.68609793,
        752450.99308496,  227498.85530721,  853325.60128355,
        777827.84576639,  653832.86026604, 1011002.08110699,
        961958.01392298,  903656.95457424,  182773.35511989,
        653747.16955906,  867286.54040054,  647759.74347208,
        274077.63824205,  510938.95299096,  457924.94286537,
        530889.51438198,  497811.68447948,  621556.54269837,
       1034773.04792341,  666442.79236862,  519753.22910723,
       1002462.36430844,  771216.81697421,  343188.3050626 ,
        442982.03972737,  549557.24128464,  481506.73394597,
        358370.23921419,  616652.48519507,  578101.81217386,
        335615.63403628,  508458.82313916,  486687.59117747,
        953918.07825462,  931853.73507168,  267511.01839668,
        819102.26222646,  164402.13575264,  985796.80249302,
        445156.2419582 ,  653634.85919137,  425806.70312081,
        760912.78235506, 1003106.12731172,  728591.2478293 ,
        630302.8866731 ,  224310.62975439,  216297.78707977,
        894743.66358266,  437859.59396004,  797368.16035785,
        396138.06252499,  393175.66305842,  362738.65300424,
        610804.21886877,  606181.45970658,  244183.77837886,
        260719.85873729,  401054.26714287,  567758.44042756,
        654197.33234777,  344844.8140632 ,  346656.49100363,
        561944.28197556,  792222.38728768,  252053.90972961,
        773460.74453834,  974460.65097324,  445039.17851797,
        374930.34463814,  227182.76335818,  967345.59793058,
        431426.25875067,  426454.83289762,  465135.84351114,
        284973.89145469,  886367.76634163,  432269.06740024,
        743412.66743095,  248550.65038969,  686809.91080663,
        213318.76308977,  419720.52439672,  543290.93514243,
        885879.77116597,  937015.71391599,  358185.96902182,
        624044.02197414,  578596.20158349,  720302.2541507 ,
        340285.84943676,  788449.68359229,  471889.71232945,
        732462.84161128,  982807.00145861,  739369.47604256,
       1043309.41582323,  723060.11892141,  334997.0866715 ,
        499389.52487925,  875141.39537729,  727416.49540406,
        486781.01869373, 1016828.47128016,  309375.66348622,
        619348.94870196,  116564.08945585,  857570.75335076,
        492414.54115223,  834286.95567504,  508817.12366864,
        286873.54987037,  891292.0661481 ,  815767.10291574,
        621303.18033757,  804979.40165288,  518029.17346684,
        644056.81675343,  988215.1972865 , 1081449.37481655,
        870531.22788699,  191797.52221473,  433306.07493533,
        817310.48201479,  253939.40924133, 1000759.05827107,
        753985.55383579,  767683.49274395,  742864.42100906,
       1016116.9693067 ,  973880.35081903,  981846.27494543,
        541024.06675969,  515877.60097628,  792867.71505599,
        528195.00966371,  680763.80843211,  459000.91099371,
        835607.98201597,  720449.60848806,  576559.26719097])

In [ ]:
print("Training efficiency: ",modelr.score(Xtrain,ytrain))
print("Testing efficiency: ",modelr.score(Xtest,ytest))

Training efficiency:  0.9995244930475269
Testing efficiency:  0.9967943613125956

In [ ]:
print("R2 score",r2_score(ytest,ypredr))
print("MAE",mean_absolute_error(ytest,ypredr))

R2 score 0.9967943613125956
MAE 11554.662640706156

# Gradient Boosting Classifier

In [ ]:
df1=pd.read_csv('/content/heart_disease.csv')
df1

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
0,56.0,Male,153.0,155.0,High,Yes,Yes,No,24.991591,Yes,...,No,High,Medium,7.633228,Medium,342.0,NaN,12.969246,12.387250,No
1,69.0,Female,146.0,286.0,High,No,Yes,Yes,25.221799,No,...,No,Medium,High,8.744034,Medium,133.0,157.0,9.355389,19.298875,No
2,46.0,Male,126.0,216.0,Low,No,No,No,29.855447,No,...,Yes,Low,Low,4.440440,Low,393.0,92.0,12.709873,11.230926,No
3,32.0,Female,122.0,293.0,High,Yes,Yes,No,24.130477,Yes,...,Yes,Low,High,5.249405,High,293.0,94.0,12.509046,5.961958,No
4,60.0,Male,166.0,242.0,Low,Yes,Yes,Yes,20.486289,Yes,...,No,Low,High,7.030971,High,263.0,154.0,10.381259,8.153887,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,25.0,Female,136.0,243.0,Medium,Yes,No,No,18.788791,Yes,...,Yes,Medium,High,6.834954,Medium,343.0,133.0,3.588814,19.132004,Yes
9996,38.0,Male,172.0,154.0,Medium,No,No,No,31.856801,Yes,...,Yes,NaN,High,8.247784,Low,377.0,83.0,2.658267,9.715709,Yes
9997,73.0,Male,152.0,201.0,High,Yes,No,Yes,26.899911,No,...,Yes,NaN,Low,4.436762,Low,248.0,88.0,4.408867,9.492429,Yes
9998,23.0,Male,142.0,299.0,Low,Yes,No,Yes,34.964026,Yes,...,Yes,Medium,High,8.526329,Medium,113.0,153.0,7.215634,11.873486,Yes
9999,38.0,Female,128.0,193.0,Medium,Yes,Yes,Yes,25.111295,No,...,Yes,High,Medium,5.659394,High,121.0,149.0,14.387810,6.208531,Yes

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Age                   9971 non-null   float64
 1   Gender                9981 non-null   object
 2   Blood Pressure        9981 non-null   float64
 3   Cholesterol Level     9970 non-null   float64
 4   Exercise Habits       9975 non-null   object
 5   Smoking               9975 non-null   object
 6   Family Heart Disease  9979 non-null   object
 7   Diabetes              9970 non-null   object
 8   BMI                   9978 non-null   float64
 9   High Blood Pressure   9974 non-null   object
 10  Low HDL Cholesterol   9975 non-null   object
 11  High LDL Cholesterol  9974 non-null   object
 12  Alcohol Consumption   7414 non-null   object
 13  Stress Level          9978 non-null   object
 14  Sleep Hours           9975 non-null   float64
 15  Sugar Consumption     9970 non-null   object
 16  Triglyceride Level    9974 non-null   float64
 17  Fasting Blood Sugar   9978 non-null   float64
 18  CRP Level             9974 non-null   float64
 19  Homocysteine Level    9980 non-null   float64
 20  Heart Disease Status  10000 non-null  object
dtypes: float64(9), object(12)
memory usage: 1.6+ MB

In [ ]:
df1.isnull().sum()

Age                       29
Gender                    19
Blood Pressure            19
Cholesterol Level         30
Exercise Habits           25
Smoking                   25
Family Heart Disease      21
Diabetes                  30
BMI                       22
High Blood Pressure       26
Low HDL Cholesterol       25
High LDL Cholesterol      26
Alcohol Consumption     2586
Stress Level              22
Sleep Hours               25
Sugar Consumption         30
Triglyceride Level        26
Fasting Blood Sugar       22
CRP Level                 26
Homocysteine Level        20
Heart Disease Status       0
dtype: int64

In [ ]:
df1.duplicated().sum()

np.int64(0)

In [ ]:
df1.dropna(inplace=True)

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7067 entries, 1 to 9999
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Age                   7067 non-null   float64
 1   Gender                7067 non-null   object
 2   Blood Pressure        7067 non-null   float64
 3   Cholesterol Level     7067 non-null   float64
 4   Exercise Habits       7067 non-null   object
 5   Smoking               7067 non-null   object
 6   Family Heart Disease  7067 non-null   object
 7   Diabetes              7067 non-null   object
 8   BMI                   7067 non-null   float64
 9   High Blood Pressure   7067 non-null   object
 10  Low HDL Cholesterol   7067 non-null   object
 11  High LDL Cholesterol  7067 non-null   object
 12  Alcohol Consumption   7067 non-null   object
 13  Stress Level          7067 non-null   object
 14  Sleep Hours           7067 non-null   float64
 15  Sugar Consumption     7067 non-null   object
 16  Triglyceride Level    7067 non-null   float64
 17  Fasting Blood Sugar   7067 non-null   float64
 18  CRP Level             7067 non-null   float64
 19  Homocysteine Level    7067 non-null   float64
 20  Heart Disease Status  7067 non-null   object
dtypes: float64(9), object(12)
memory usage: 1.2+ MB

In [ ]:
df1.head()

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
1,69.0,Female,146.0,286.0,High,No,Yes,Yes,25.221799,No,...,No,Medium,High,8.744034,Medium,133.0,157.0,9.355389,19.298875,No
2,46.0,Male,126.0,216.0,Low,No,No,No,29.855447,No,...,Yes,Low,Low,4.440440,Low,393.0,92.0,12.709873,11.230926,No
3,32.0,Female,122.0,293.0,High,Yes,Yes,No,24.130477,Yes,...,Yes,Low,High,5.249405,High,293.0,94.0,12.509046,5.961958,No
4,60.0,Male,166.0,242.0,Low,Yes,Yes,Yes,20.486289,Yes,...,No,Low,High,7.030971,High,263.0,154.0,10.381259,8.153887,No
5,25.0,Male,152.0,257.0,Low,Yes,No,No,28.144681,No,...,No,Low,Medium,5.504876,Low,126.0,91.0,4.297575,10.815983,No

In [ ]:
df1['Exercise Habits'].unique()

array(['High', 'Low', 'Medium'], dtype=object)

In [ ]:
df1.drop_duplicates(inplace=True)

In [ ]:
df1.shape

(7067, 21)

In [ ]:
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder

In [ ]:
LE=LabelEncoder()
OE=OrdinalEncoder(categories=[['Low','Medium','High']])

In [ ]:
# df1.columns

In [ ]:
for col in df1.columns:
  if df1[col].dtype==object:
    if 'High' in df1[col].unique():
      df1[col]=OE.fit_transform(df1[[col]])
    else:
      df1[col]=LE.fit_transform(df1[col])
df1

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
1,69.0,0,146.0,286.0,2.0,0,1,1,25.221799,0,...,0,1.0,2.0,8.744034,1.0,133.0,157.0,9.355389,19.298875,0
2,46.0,1,126.0,216.0,0.0,0,0,0,29.855447,0,...,1,0.0,0.0,4.440440,0.0,393.0,92.0,12.709873,11.230926,0
3,32.0,0,122.0,293.0,2.0,1,1,0,24.130477,1,...,1,0.0,2.0,5.249405,2.0,293.0,94.0,12.509046,5.961958,0
4,60.0,1,166.0,242.0,0.0,1,1,1,20.486289,1,...,0,0.0,2.0,7.030971,2.0,263.0,154.0,10.381259,8.153887,0
5,25.0,1,152.0,257.0,0.0,1,0,0,28.144681,0,...,0,0.0,1.0,5.504876,0.0,126.0,91.0,4.297575,10.815983,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9992,68.0,0,169.0,291.0,1.0,1,0,0,22.839718,0,...,0,1.0,0.0,6.057509,2.0,299.0,142.0,3.321020,11.910244,1
9994,73.0,0,144.0,191.0,1.0,1,1,1,39.459620,0,...,0,1.0,0.0,7.549114,1.0,200.0,88.0,1.154904,8.021732,1
9995,25.0,0,136.0,243.0,1.0,1,0,0,18.788791,1,...,1,1.0,2.0,6.834954,1.0,343.0,133.0,3.588814,19.132004,1
9998,23.0,1,142.0,299.0,0.0,1,0,1,34.964026,1,...,1,1.0,2.0,8.526329,1.0,113.0,153.0,7.215634,11.873486,1
9999,38.0,0,128.0,193.0,1.0,1,1,1,25.111295,0,...,1,2.0,1.0,5.659394,2.0,121.0,149.0,14.387810,6.208531,1

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7067 entries, 1 to 9999
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Age                   7067 non-null   float64
 1   Gender                7067 non-null   int64
 2   Blood Pressure        7067 non-null   float64
 3   Cholesterol Level     7067 non-null   float64
 4   Exercise Habits       7067 non-null   float64
 5   Smoking               7067 non-null   int64
 6   Family Heart Disease  7067 non-null   int64
 7   Diabetes              7067 non-null   int64
 8   BMI                   7067 non-null   float64
 9   High Blood Pressure   7067 non-null   int64
 10  Low HDL Cholesterol   7067 non-null   int64
 11  High LDL Cholesterol  7067 non-null   int64
 12  Alcohol Consumption   7067 non-null   float64
 13  Stress Level          7067 non-null   float64
 14  Sleep Hours           7067 non-null   float64
 15  Sugar Consumption     7067 non-null   float64
 16  Triglyceride Level    7067 non-null   float64
 17  Fasting Blood Sugar   7067 non-null   float64
 18  CRP Level             7067 non-null   float64
 19  Homocysteine Level    7067 non-null   float64
 20  Heart Disease Status  7067 non-null   int64
dtypes: float64(13), int64(8)
memory usage: 1.2 MB

In [ ]:
X=df1.iloc[:,:-1]
y=df1.iloc[:,-1]

In [ ]:
Xtrain,Xtest,ytrain,ytest=train_test_split(X,y,test_size=0.3,random_state=42)

In [ ]:
modelc=GradientBoostingClassifier(n_estimators=200,learning_rate=0.03)
modelc.fit(Xtrain,ytrain)

GradientBoostingClassifier(learning_rate=0.03, n_estimators=200)

In [ ]:
ypredc=modelc.predict(Xtest)
ypredc

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
print("Training efficiency: ",modelc.score(Xtrain,ytrain))
print("Testing efficiency: ",modelc.score(Xtest,ytest))

Training efficiency:  0.8026688232915488
Testing efficiency:  0.7897218293257897