# Linear Regression

In [ ]:
import pandas as pd
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score,mean_absolute_error

In [ ]:
#loading our dataset
df= pd.read_csv("https://raw.githubusercontent.com/Jeevita-R/ML_datasets/refs/heads/main/House_price_prediction.csv")
df

,Unnamed: 0,Suburb,Rooms,Type,Method,SellerG,Regionname,Propertycount,Distance,CouncilArea,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Price
0,1,Abbotsford,2,h,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,2.0,1.0,1.0,202.000000,160.2564,1480000.0
1,2,Abbotsford,2,h,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,2.0,1.0,0.0,156.000000,79.0000,1035000.0
2,4,Abbotsford,3,h,SP,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,3.0,2.0,0.0,134.000000,150.0000,1465000.0
3,5,Abbotsford,3,h,PI,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,3.0,2.0,1.0,94.000000,160.2564,850000.0
4,6,Abbotsford,4,h,VB,Nelson,Northern Metropolitan,4019.0,2.5,Yarra City Council,3.0,1.0,2.0,120.000000,142.0000,1600000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27239,34852,Yarraville,4,h,PI,Jas,Western Metropolitan,6543.0,6.3,Maribyrnong City Council,4.0,1.0,3.0,593.000000,160.2564,1480000.0
27240,34853,Yarraville,2,h,SP,Sweeney,Western Metropolitan,6543.0,6.3,Maribyrnong City Council,2.0,2.0,1.0,98.000000,104.0000,888000.0
27241,34854,Yarraville,2,t,S,Jas,Western Metropolitan,6543.0,6.3,Maribyrnong City Council,2.0,1.0,2.0,220.000000,120.0000,705000.0
27242,34855,Yarraville,3,h,SP,hockingstuart,Western Metropolitan,6543.0,6.3,Maribyrnong City Council,0.0,0.0,0.0,593.598993,160.2564,1140000.0
27243,34856,Yarraville,2,h,PI,RW,Western Metropolitan,6543.0,6.3,Maribyrnong City Council,2.0,1.0,0.0,250.000000,103.0000,1020000.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27244 entries, 0 to 27243
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     27244 non-null  int64
 1   Suburb         27244 non-null  object
 2   Rooms          27244 non-null  int64
 3   Type           27244 non-null  object
 4   Method         27244 non-null  object
 5   SellerG        27244 non-null  object
 6   Regionname     27244 non-null  object
 7   Propertycount  27244 non-null  float64
 8   Distance       27244 non-null  float64
 9   CouncilArea    27244 non-null  object
 10  Bedroom2       27244 non-null  float64
 11  Bathroom       27244 non-null  float64
 12  Car            27244 non-null  float64
 13  Landsize       27244 non-null  float64
 14  BuildingArea   27244 non-null  float64
 15  Price          27244 non-null  float64
dtypes: float64(8), int64(2), object(6)
memory usage: 3.3+ MB

In [ ]:
df = pd.get_dummies(df,drop_first=True,dtype=int)
df

,Unnamed: 0,Rooms,Propertycount,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Price,...,CouncilArea_Moorabool Shire Council,CouncilArea_Moreland City Council,CouncilArea_Nillumbik Shire Council,CouncilArea_Port Phillip City Council,CouncilArea_Stonnington City Council,CouncilArea_Whitehorse City Council,CouncilArea_Whittlesea City Council,CouncilArea_Wyndham City Council,CouncilArea_Yarra City Council,CouncilArea_Yarra Ranges Shire Council
0,1,2,4019.0,2.5,2.0,1.0,1.0,202.000000,160.2564,1480000.0,...,0,0,0,0,0,0,0,0,1,0
1,2,2,4019.0,2.5,2.0,1.0,0.0,156.000000,79.0000,1035000.0,...,0,0,0,0,0,0,0,0,1,0
2,4,3,4019.0,2.5,3.0,2.0,0.0,134.000000,150.0000,1465000.0,...,0,0,0,0,0,0,0,0,1,0
3,5,3,4019.0,2.5,3.0,2.0,1.0,94.000000,160.2564,850000.0,...,0,0,0,0,0,0,0,0,1,0
4,6,4,4019.0,2.5,3.0,1.0,2.0,120.000000,142.0000,1600000.0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27239,34852,4,6543.0,6.3,4.0,1.0,3.0,593.000000,160.2564,1480000.0,...,0,0,0,0,0,0,0,0,0,0
27240,34853,2,6543.0,6.3,2.0,2.0,1.0,98.000000,104.0000,888000.0,...,0,0,0,0,0,0,0,0,0,0
27241,34854,2,6543.0,6.3,2.0,1.0,2.0,220.000000,120.0000,705000.0,...,0,0,0,0,0,0,0,0,0,0
27242,34855,3,6543.0,6.3,0.0,0.0,0.0,593.598993,160.2564,1140000.0,...,0,0,0,0,0,0,0,0,0,0
27243,34856,2,6543.0,6.3,2.0,1.0,0.0,250.000000,103.0000,1020000.0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27244 entries, 0 to 27243
Columns: 746 entries, Unnamed: 0 to CouncilArea_Yarra Ranges Shire Council
dtypes: float64(8), int64(738)
memory usage: 155.1 MB

In [ ]:
df=df.drop("Unnamed: 0",axis=1)

In [ ]:
df

,Rooms,Propertycount,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Price,Suburb_Aberfeldie,...,CouncilArea_Moorabool Shire Council,CouncilArea_Moreland City Council,CouncilArea_Nillumbik Shire Council,CouncilArea_Port Phillip City Council,CouncilArea_Stonnington City Council,CouncilArea_Whitehorse City Council,CouncilArea_Whittlesea City Council,CouncilArea_Wyndham City Council,CouncilArea_Yarra City Council,CouncilArea_Yarra Ranges Shire Council
0,2,4019.0,2.5,2.0,1.0,1.0,202.000000,160.2564,1480000.0,0,...,0,0,0,0,0,0,0,0,1,0
1,2,4019.0,2.5,2.0,1.0,0.0,156.000000,79.0000,1035000.0,0,...,0,0,0,0,0,0,0,0,1,0
2,3,4019.0,2.5,3.0,2.0,0.0,134.000000,150.0000,1465000.0,0,...,0,0,0,0,0,0,0,0,1,0
3,3,4019.0,2.5,3.0,2.0,1.0,94.000000,160.2564,850000.0,0,...,0,0,0,0,0,0,0,0,1,0
4,4,4019.0,2.5,3.0,1.0,2.0,120.000000,142.0000,1600000.0,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27239,4,6543.0,6.3,4.0,1.0,3.0,593.000000,160.2564,1480000.0,0,...,0,0,0,0,0,0,0,0,0,0
27240,2,6543.0,6.3,2.0,2.0,1.0,98.000000,104.0000,888000.0,0,...,0,0,0,0,0,0,0,0,0,0
27241,2,6543.0,6.3,2.0,1.0,2.0,220.000000,120.0000,705000.0,0,...,0,0,0,0,0,0,0,0,0,0
27242,3,6543.0,6.3,0.0,0.0,0.0,593.598993,160.2564,1140000.0,0,...,0,0,0,0,0,0,0,0,0,0
27243,2,6543.0,6.3,2.0,1.0,0.0,250.000000,103.0000,1020000.0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
#dividing the data
X=df.drop("Price",axis=1)
y=df.Price
X
y

0        1480000.0
1        1035000.0
2        1465000.0
3         850000.0
4        1600000.0
           ...
27239    1480000.0
27240     888000.0
27241     705000.0
27242    1140000.0
27243    1020000.0
Name: Price, Length: 27244, dtype: float64

In [ ]:
Xtrain,Xtest,ytrain,ytest=train_test_split(X,y,test_size=0.3,random_state=2)

In [ ]:
Lr= LinearRegression()

In [ ]:
Lr.fit(Xtrain,ytrain)

LinearRegression()

In [ ]:
ypred=Lr.predict(Xtest)
ypred

array([1672988.74421205, 1086049.7213438 ,  852828.7900154 , ...,
        891754.56465554,  783898.88694696, 1170611.7469903 ])

In [ ]:
print("Training: ",Lr.score(Xtrain,ytrain))
print("Testing: ",Lr.score(Xtest,ytest))

Training:  0.6827792395792723
Testing:  0.13853683161594055

In [ ]:
print("MAE: ",mean_absolute_error(ytest,ypred))

MAE:  246805.62890777894

# Ridge Regression

In [ ]:
ridge = Ridge(alpha=5)
ridge.fit(Xtrain,ytrain)

Ridge(alpha=5)

In [ ]:
ypred = ridge.predict(Xtest)
ypred

array([1678284.16402846, 1073858.18234392,  905634.78011123, ...,
        905913.71557012,  787603.15131782, 1195174.43408859])

In [ ]:
print("Training Eff: ",ridge.score(Xtrain,ytrain))
print("Testing Eff: ",ridge.score(Xtest,ytest))

Training Eff:  0.6768851181317722
Testing Eff:  0.6743855819360092

# Lasso Regression

In [ ]:
lasso = Lasso(alpha=5)

In [ ]:
lasso.fit(Xtrain,ytrain)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.273e+15, tolerance: 7.963e+11
  model = cd_fast.enet_coordinate_descent(

Lasso(alpha=5)

In [ ]:
ypred = lasso.predict(Xtest)
ypred

array([1673137.67211468, 1087422.41871567,  857126.50587502, ...,
        895345.74259798,  786981.66181643, 1175880.50466934])

In [ ]:
print("Training Eff: ",lasso.score(Xtrain,ytrain))
print("Testing Eff: ",lasso.score(Xtest,ytest))

Training Eff:  0.6825728637139723
Testing Eff:  0.22748650767597212