# ADA-BOOST classifiers

In [ ]:
import pandas as pd
import numpy as np
from sklearn.ensemble import AdaBoostClassifier,AdaBoostRegressor
from sklearn.tree import DecisionTreeClassifier,DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,recall_score,r2_score,mean_absolute_error
from sklearn.datasets import make_classification, make_regression# creating synthatic datasets--> random datat

In [ ]:
# we use n_classes=2 for classification
x,y=make_classification(n_samples=1000,n_features=5,n_classes=2,random_state=42)
# n_samples=1000 -->number of row in dataset
#n_features=5 --> how many featues we want in dataset--> we have 5 different data in input column
#n_classes=2 --> how many classes in output column in y we have "0" and "1"

In [ ]:
x

array([[-0.43964281,  0.54254734, -0.82241993,  0.40136622, -0.85484   ],
       [ 2.82223116, -2.48085944, -1.14769139, -2.10113103,  3.04027792],
       [ 1.61838572, -1.36947785, -2.08411294, -1.17965857,  1.61360231],
       ...,
       [ 1.56038977, -0.22904063, -0.2344078 , -0.61957623, -1.10985576],
       [ 0.88692467, -0.22294581, -1.3088204 , -0.39617745, -0.40427827],
       [-2.74710392,  1.85043021, -0.19382614,  1.77741855, -1.58083381]])

In [ ]:
y

array([0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0])

In [ ]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=42)

In [ ]:
base_model=DecisionTreeClassifier(max_depth=1)
model=AdaBoostClassifier(estimator=base_model,n_estimators=300,random_state=42)
model.fit(xtrain,ytrain)

AdaBoostClassifier(estimator=DecisionTreeClassifier(max_depth=1),
                   n_estimators=300, random_state=42)

In [ ]:
ypredc=model.predict(xtest)

In [ ]:
print("trining efficiency",model.score(xtrain,ytrain))
print("testing efficiency",model.score(xtest,ytest))

trining efficiency 0.9042857142857142
testing efficiency 0.87

In [ ]:
confusion_matrix(ytest,ypredc)

array([[135,  11],
       [ 28, 126]])

In [ ]:
print("precision_score:",precision_score(ytest,ypredc))
print("recall_score",recall_score(ytest,ypredc))

precision_score: 0.9197080291970803
recall_score 0.8181818181818182

# ADDABOOST Regression

In [ ]:
# we use n_informative=2 for regressions
x,y=make_regression(n_samples=1000,n_features=5,n_informative=2,random_state=42)
# n_samples=1000 -->number of row in dataset
#n_features=5 --> how many featues we want in dataset--> we have 5 different data in input column
#n_classes=2 --> how many classes in output column in y we have "0" and "1"

In [ ]:
x

array([[-0.62631528,  0.49406392, -2.85462666, -0.85685187, -1.12605396],
       [-0.02502696,  0.8177663 ,  1.39020755,  0.55781031,  0.01035262],
       [-1.42225371, -0.64657288, -1.081548  ,  1.68714164,  0.88163976],
       ...,
       [-2.0820987 ,  0.55314916, -0.5482003 ,  1.92344579, -0.77461497],
       [ 0.55832691,  0.07600539,  0.53875599, -0.92067359,  0.16936082],
       [ 1.67737709, -0.80517175,  1.07684814, -2.16967742, -1.1941894 ]])

In [ ]:
y

array([-1.15292357e+00,  1.51111782e+01, -3.62081754e+01, -1.03050758e+01,
        1.71316767e+00,  1.64526923e+01,  2.07794837e+01, -9.30345195e+00,
        2.68393050e+01, -1.64206933e+01, -5.85631612e+00, -9.20428786e+00,
       -2.17402654e+01,  8.71567510e+00,  8.06237825e+00, -1.72480134e+01,
       -2.24796104e+01, -1.42431431e+01,  3.08712378e+00, -1.46483960e+01,
        2.23226050e+01,  7.10845648e+00,  1.81463712e+01,  1.14173741e+01,
       -3.18012293e+01, -5.86388405e+01,  1.34949634e+01,  2.60556981e+01,
        3.31256878e+01,  4.25176019e+00, -1.06344700e+01,  2.13982268e+01,
        8.19965888e+00, -1.03942549e+01, -4.83488563e+01, -1.96592504e+01,
       -1.37062041e+01, -2.36953567e+01, -2.10339435e+01, -6.61098943e+00,
       -2.18091964e+01, -4.23000931e+01,  2.65562397e+01, -2.38328261e+01,
        6.26251580e+00, -1.08005080e+01, -2.47855820e+01,  4.61861614e+00,
        1.52215746e+01, -7.79347006e+01, -3.03105681e+01,  4.91923603e+01,
       -6.15530141e+00,  2.86081971e+01,  1.34201449e+01,  4.16193301e+01,
       -2.70057948e+00, -3.33546112e+01, -5.72721275e+01, -8.59926547e+00,
       -3.60222237e+01, -4.77980592e+00, -1.28308466e+01, -1.84808895e+01,
       -2.34756258e+01,  5.42428349e+01, -4.12053472e+01,  2.13684767e+01,
       -4.13966440e+01, -2.45865127e+01, -3.02452219e+00,  2.03692971e+01,
       -5.27287322e+00, -3.25355369e+00,  8.40974062e+00,  1.13606474e+01,
       -1.84025647e+01,  2.97449357e+01, -2.54113646e+01,  2.99294774e+01,
        5.49479839e-01,  1.94461495e+01,  3.61361214e+01,  8.74196215e+00,
       -1.84171732e+01, -1.10763105e+01, -3.18565538e+00, -1.20510697e+01,
        4.64363230e+01,  2.67825887e+01,  1.33060177e+01,  3.29098243e+01,
       -4.96840732e+00, -4.25505628e+01, -3.88484175e+01,  2.79607881e+01,
        2.78424871e+01, -2.03010747e+01,  1.31627677e+01,  8.60922269e+00,
       -1.46678479e+01,  2.19953453e+01, -5.34177585e+00,  1.33040171e+01,
        2.04993366e+01,  1.07451906e+01,  3.31983139e+01,  5.25035888e+01,
        2.77657933e+01, -3.97371861e+01, -6.89048361e+00, -1.61554846e+01,
        1.72073959e+01,  1.75357990e+01,  5.94413078e+01, -8.97423058e+00,
        9.02130698e+00,  1.60996298e+01, -2.37167782e+00, -3.65513185e+01,
       -8.73950835e+00, -2.28403648e+01, -1.94613116e+01,  1.75001107e+01,
        6.18562518e+00,  1.97568693e+01, -1.43467874e+00,  2.27214524e+01,
       -5.36389148e+00, -8.35755662e+00,  7.70672540e+00,  3.44681962e+00,
       -7.91671917e+00, -1.87108175e+01, -2.23732480e+01,  1.94789265e+01,
       -2.76182102e+01,  5.23520941e+01, -3.40870067e+01, -1.98000073e+01,
        8.55112957e+00,  1.79203316e+01,  1.90893697e+01,  2.68781818e+00,
        7.29049358e+01, -4.69777633e+01, -3.76200353e+00, -2.70900816e+01,
        3.75266769e+01, -1.09298144e+00,  1.02330186e+01, -1.10802957e-01,
       -3.17937162e+01,  3.65880676e+00,  7.15271816e+00, -1.57163228e+01,
        4.13112510e+01, -2.53753395e+01,  2.75929623e+00,  5.27120872e+01,
        1.41727088e+01,  1.67374344e+01,  1.14278872e+01, -8.82340437e+00,
       -1.94468496e+01, -3.74376380e+01, -2.86969150e+01, -7.27049147e+00,
       -2.90065366e+01, -6.23883363e+01,  5.51223588e+01, -2.01549142e+00,
       -5.13375552e+00, -3.20586557e+00, -4.78817983e+00,  3.38875403e+01,
       -2.04660609e+01, -1.41244980e+01,  4.78465684e+01,  5.06648086e+01,
       -1.66422069e+01, -1.71202037e+01,  1.14601240e+01, -3.96437644e+00,
        1.95170044e+01,  5.38880359e+01,  4.80455673e+01, -1.99437889e+01,
        7.60260569e+00,  1.37045371e+01,  3.28932764e+01,  2.02828162e+00,
       -5.43651925e+01, -1.66076396e+01, -5.58635638e+01, -2.13210473e+00,
        8.94527780e+00, -3.03943025e+01, -1.07803523e+01, -2.34495571e+01,
       -2.59236810e+01,  4.14050483e+00,  2.94654374e+01,  2.62594870e+00,
       -1.61603552e+01, -4.41531071e+01,  2.10005268e+01, -5.86061803e+00,
        1.57927699e+01, -1.81393379e+01, -1.20635173e+01,  1.21682231e+01,
        4.53093479e+01,  2.66974305e+01, -1.01552961e+00,  6.45643658e+01,
       -2.41548003e+01,  1.12040942e+01, -1.83276608e+01, -1.40168063e+01,
        5.96481373e+01,  2.59138575e+01,  8.50265386e-01,  1.24990583e+01,
       -3.26030478e+01, -1.61906135e+01,  2.77924291e+01, -1.28651782e+01,
       -8.73403615e+00,  7.41446981e+00,  2.03958653e+01,  1.69665935e+01,
        1.63443418e+01,  1.61370278e+01,  2.35325778e+01,  4.71025973e+01,
        9.10246000e+00,  1.16230579e+01, -1.24726673e+01,  1.56261790e+01,
       -2.47161029e+01, -3.30918409e+00,  1.51680043e+01, -1.24992215e+01,
       -1.15877725e+01, -2.60816557e+01,  2.45580565e+01,  1.28383078e+01,
       -1.06638482e+01, -3.24388480e+01,  6.29495673e+01, -1.53153832e+01,
        2.00311333e+01,  1.21324886e+01, -4.87142737e+01, -3.67782876e+01,
        2.49174770e+01, -3.52738778e+01, -3.22362057e+01,  6.04765002e+01,
        3.08328221e+01,  1.09277325e+00,  1.73265011e+01,  2.34384078e+01,
       -9.65839141e+00, -6.36337845e+00, -7.33411788e+00, -7.48538044e-01,
       -1.81531029e+01, -3.53963689e+01,  7.40375966e+00,  1.11724607e+01,
        3.21512336e+01, -5.61257435e+01,  6.75093442e+00,  4.21591973e+01,
        1.01952405e+00, -2.19301258e+00, -1.37085389e+01,  4.25552633e+00,
       -1.52878647e+01,  1.20591463e+01,  1.11960060e+01,  5.97431458e+00,
       -2.61866631e+00,  3.52926541e+01, -1.72178399e+01,  1.31405018e+01,
       -4.99341065e+00,  3.73841429e+00,  2.09111477e+01,  2.34195365e+01,
        1.20179927e+01,  5.41115760e+01, -1.88756902e+01,  2.97597858e+01,
       -2.49370116e+00, -2.35084801e+01, -1.71367761e+01, -3.96817727e+01,
        1.10137647e+01,  1.88637693e+01, -2.01907929e+01, -1.29760361e+01,
        1.97525891e+01, -8.71391602e+00, -1.56415228e+01, -1.74957363e+01,
       -1.03408711e+01,  2.37127691e+00,  2.13009503e+01, -2.10055092e+00,
       -2.49904609e+01,  3.29284611e+01, -3.82083196e+01,  3.80962080e+01,
        9.95307793e+00,  9.36333495e+00, -1.51756692e+01, -1.12501041e+01,
       -2.16297451e+00, -1.16846192e+01,  2.42354548e+01, -2.08145776e+01,
        7.92191863e+00, -2.81179376e+01, -2.09501113e+01, -1.32754086e+01,
       -6.04916894e+00, -4.72053468e+01,  2.94484031e+01,  4.47259820e+01,
        5.73042953e+00,  7.94840233e+00, -7.59379192e+00,  4.42419995e+01,
       -5.10758165e+01,  8.09038366e+00,  1.50419947e+01,  7.75436619e+00,
        1.32475300e+01,  9.46559118e+00,  3.72909848e+01,  1.63386899e+01,
       -9.62697221e+00,  2.51909216e+01,  2.62977020e+01, -4.15318308e+01,
       -3.87201074e+01,  2.13806012e+00, -1.24028388e+01, -6.49285430e-01,
        2.26528620e+01, -2.03921802e+01,  5.22005082e+00,  1.11564150e+01,
       -2.40056637e+01, -7.11190961e+00,  5.18481502e+01, -9.81450488e-01,
       -1.15351340e+01,  7.15273818e+01, -1.06476205e+01, -1.45905938e+01,
       -3.88978688e+01,  2.63779400e+01, -1.77777604e+01,  3.69476137e+01,
        1.41631991e+01, -1.24945526e+01, -1.65720106e+01, -1.09869820e+01,
       -1.40951778e+01, -1.99203471e+01,  2.14491959e+01, -4.96372899e+00,
        1.37498401e+01,  1.19850062e+01, -1.40358814e+01, -2.38165215e+01,
       -2.36002241e+01, -3.51592237e+01, -3.12185857e+01, -1.98858912e+01,
        3.15983110e+01, -9.98628219e+00,  5.42925318e+00,  1.56785882e+01,
        2.62828224e+00, -1.04496181e+01,  7.43979822e+00,  7.39193511e-01,
       -1.48413636e+01, -7.41997194e+00,  1.54022077e+00,  1.40036942e+01,
       -1.04905991e+01,  8.27128696e+00,  1.66705387e+01, -5.37550731e+01,
        2.30270238e+01, -2.54122733e+01, -5.76828290e-01, -1.50009462e+00,
        4.21271250e+01,  2.21887289e+01,  7.71894198e+00,  9.32940721e+00,
        1.38286338e+01,  1.25526376e+01,  6.12312782e+00, -1.18278335e+01,
        1.11988649e+01,  5.66358973e+00, -3.57241837e+01, -1.44823975e+00,
       -3.60656557e+00,  1.13809995e+01, -1.23933189e+01, -3.12128932e+01,
       -1.30703210e+01,  5.84039887e+00, -3.07383856e+00,  1.36516604e+01,
       -1.95224889e+00,  1.26083632e+00,  5.38809191e+01, -4.24106290e+01,
        6.19912200e+00, -5.45264004e+01, -2.78431479e+01, -7.23299370e+01,
       -1.13463747e+01, -3.26897227e+01, -5.53241168e+00, -3.27042853e+01,
        3.39947210e+01, -2.49319399e+01,  3.93805608e+01, -4.34274427e+01,
        2.68035359e+01, -4.00320408e+01, -9.86823153e+00,  2.03601279e+00,
       -2.68704810e+01,  4.29855055e+01, -5.75438665e+00,  4.30022460e-01,
        1.53839649e+01, -5.39658891e+01,  7.75973728e+01, -2.35649776e+01,
       -2.73965514e+01, -2.77996570e+01, -3.00656863e+00,  3.50549058e+01,
        4.11042833e+01, -4.00669677e+01, -2.61189067e+00, -1.85901680e+01,
       -6.36454862e+00,  3.11217943e+01, -8.66231589e+00, -1.77652055e+01,
        1.46460171e+01, -2.01297033e+00,  1.25802656e+01,  3.33897399e+01,
       -1.11403754e+01, -4.91491646e+01,  4.46273337e+01, -1.67249545e+01,
       -3.46037467e-01,  3.78493453e+01, -1.29538738e+00,  1.92411336e+01,
       -2.44608851e+00,  2.03341343e+01,  5.97008123e+00,  4.50014611e+00,
        5.40860192e-01, -1.70736884e+01, -2.22696141e+01,  5.59673381e+01,
        2.72290430e+01,  1.65576045e+01,  1.26883877e+01, -1.82595311e+01,
        2.64691344e+01,  1.68776254e+01, -3.14138300e+01,  2.57813460e+01,
       -1.90936486e+01,  3.94746505e+01,  1.80377498e+01,  9.30020874e+00,
       -1.32231931e+01,  3.05198892e-02,  6.37813194e+00,  2.25326294e+01,
       -1.54299418e+01,  2.85985767e+01,  1.68189691e+01,  2.24040618e+01,
        1.00211572e+01,  2.63892217e+01, -4.68576039e+00,  1.58118948e+01,
        1.13366018e+01,  2.20925356e+01,  2.94267497e+01, -2.28280029e+01,
       -5.99533851e+00,  5.20792692e+00, -1.37144907e+01, -1.40439950e+01,
        2.24641650e+01, -1.76899438e+01, -2.62703675e+00,  1.76954599e+01,
       -1.08794590e+01, -1.98376730e+01, -1.25903208e+00, -3.90906197e+01,
        4.41383222e+00,  1.50265021e+01,  6.60401964e+00, -3.27974386e+00,
        2.98213046e+01,  5.97320682e+00, -9.79920707e+00, -8.28492051e+00,
        6.10331816e+01, -1.82292703e+01,  3.21796129e+01, -2.60650220e+01,
        2.95510938e+01,  1.28137126e+01, -1.34413947e+01, -6.30551792e+00,
       -3.41778642e+01, -1.09740673e+01,  1.29359266e+01, -4.58624009e+01,
       -3.68818994e+01,  3.11728035e+01,  1.68694838e+01,  1.59759712e+01,
        1.51654690e+01,  3.32527430e+01, -2.33872439e+01,  6.59108194e+00,
       -1.07495790e+01,  1.94974619e+01, -1.48865512e+00, -1.61292204e+00,
        9.06682584e+00, -4.98888874e+00, -5.39114505e+01, -6.80932447e-01,
       -6.35263631e+01,  2.04042536e+01,  2.06653890e+01,  3.22558723e+00,
        1.62402295e+01, -4.04572260e+00,  5.54913780e+01, -2.74514828e+00,
       -2.49232453e+01,  2.28531328e+01, -1.20308690e+01,  5.90368169e+01,
        5.94106324e+01,  1.37771488e+01, -1.73216668e+01, -1.52983036e+01,
        5.60186347e+00, -3.12765848e+01,  2.28726814e+01, -6.12774046e+01,
       -1.35192697e+00, -2.23420728e+01,  2.03597907e+01, -3.77929295e+00,
       -2.61576576e+01, -4.34384967e+00,  3.37876995e+01, -3.24785988e+01,
        9.44248811e-01,  2.30366929e+01, -3.05235750e+00,  2.41797864e+01,
       -3.62414432e+01,  1.22377816e+00, -1.51197837e+01, -1.76434253e+01,
       -3.78716902e+01, -3.38272277e+01, -1.37192192e+01,  2.26965391e+01,
        3.65117228e+00, -5.14518014e+01,  2.59164901e+01,  1.25652207e+01,
        1.44859390e+01,  1.51902441e+01, -1.18262484e+01, -1.21187676e+01,
       -1.24040501e+01, -4.02277848e+01, -1.38294625e+01,  6.38439848e+01,
       -3.38798467e+00, -2.91952934e+00, -3.79053227e+01, -7.35238955e+01,
        5.36561163e+01, -2.40925089e+01,  4.69178648e+01, -2.58864458e+00,
        5.40842620e+01, -4.18189999e+01, -1.82720339e+01,  1.70869795e+01,
        2.35973146e+01, -3.89861049e+01,  2.36226930e+01,  1.90228933e+01,
       -3.24107721e+01,  1.56945533e+00, -3.49751926e+01,  2.96017058e+01,
       -4.30097025e+01, -1.12514778e+01,  7.99483010e-01,  9.20160767e+00,
        1.17060487e+01,  1.95527064e+01, -5.09470574e+01,  2.07311534e+01,
        4.51543373e+00, -5.52738506e+01, -3.30545040e+00,  1.15551060e+01,
       -2.00105461e+01,  1.79914829e+01,  1.91864340e+01, -4.84380024e+01,
        3.98342924e+01,  2.33217383e+01,  8.38261061e+00, -1.99952433e+01,
       -4.49173838e+00, -2.57797431e+01,  4.90984881e+01, -3.58411095e+01,
       -7.10925060e+00,  3.46531062e+01, -1.48395384e+01, -4.08854961e+01,
       -1.41038800e+01, -1.30366583e+01, -9.48451176e+00,  1.21995820e-01,
        1.36201108e+01,  3.02652040e+01,  1.28815650e+01, -8.78382300e+00,
        1.59469296e+01, -1.53718997e+01, -2.08595434e+01, -2.02398020e+01,
       -2.21484197e+00,  3.60581724e+01,  5.78028828e-01, -7.36694358e+00,
        1.99143907e+01,  6.34782208e+00, -2.60074131e+00,  1.80657206e+01,
       -1.97624496e+01, -2.25957223e+01,  5.93941051e+01,  1.83177946e+01,
        7.26946949e+00,  2.51552162e+01,  9.67416223e+00,  1.09818865e+01,
       -2.19801476e+00,  1.42319216e+01,  2.53531201e-01, -1.88817747e+01,
        5.07169993e+00, -2.75199957e+01, -2.55117419e+01,  3.87426505e+01,
        5.98992323e+00, -4.05180600e+01,  6.27663783e+00, -2.54305775e+01,
        7.90559333e+00, -1.22459907e+01,  1.54807328e+01,  2.86538905e+01,
       -4.03798553e+01,  1.92733720e+01,  9.87106857e+00, -1.45516219e+01,
        1.37869741e+01, -2.93625153e+01,  1.53360232e+01, -6.18650548e+00,
        4.15300749e+01, -1.52131719e+01, -3.40497302e+00, -2.90562928e+01,
       -4.44035763e+01,  4.16857817e+01, -2.31715903e+01,  4.78235893e+00,
        2.11233455e+01, -3.34747225e+01, -6.67544033e-01, -1.08236365e+01,
        2.67298091e+01,  1.35607340e-01,  2.29626913e+01,  3.49874907e+00,
       -3.04599582e+01, -2.72118372e-01,  2.72304348e+01, -1.86177259e+00,
        4.11448198e+01, -7.92027433e+00,  7.94764252e+00,  1.13957496e+01,
        1.96140169e+01,  6.73377102e+01,  6.63704559e+00,  5.68877227e+00,
       -5.55343007e+00, -2.63774740e+01,  2.55261525e+01, -7.05135889e+00,
       -2.25424773e+01, -1.55123415e+01,  2.60513906e+01,  7.43062739e+00,
       -2.12262671e+00, -4.57323625e+01, -9.21612235e+00,  4.03202352e+01,
        8.54982281e+00, -1.90106725e+01,  5.52180176e+01, -3.62347734e+01,
        2.94151778e+01, -1.45802599e+01, -2.28856531e+01, -9.38889547e+00,
       -5.22747337e+00, -1.33331283e+01,  1.63557717e+01,  2.34041620e+00,
       -3.45997575e+01, -3.89436248e+00, -4.11209261e+01, -1.88390810e+01,
       -4.93381164e+01,  1.27064308e+01,  6.35528655e+00, -2.09984730e+01,
        3.34185031e+01, -1.69554829e+01,  5.56730137e+01,  8.49749756e+00,
        4.89013503e+01, -1.29407539e+00,  3.88569956e+00,  3.88116500e+01,
        3.24292043e+01, -1.04608767e+01, -9.55458561e+00, -1.91157469e+00,
       -1.55448202e+01,  3.47517034e+00, -4.10675903e+01,  8.09250081e+00,
        3.54753499e+01,  3.40217643e+01, -1.22058732e+01, -1.90999737e+00,
        3.06900041e+00, -3.01881961e+01, -1.17845224e+01, -2.46439643e+00,
        7.94783697e+00, -4.54888124e+00, -1.69519780e+01, -2.05455044e+01,
       -3.92746462e+00,  4.46574465e+01,  4.42941449e+01, -1.26503604e+01,
        2.25582637e+01,  1.00128849e+01,  2.41543301e+00, -3.73691734e+01,
        5.98388346e+00,  2.22226013e+01,  1.59395542e+01, -9.82313943e-01,
       -2.13138769e+01, -2.55830133e+01,  8.75397374e+00, -1.93649458e+01,
       -3.18751274e+01,  3.02652676e+01,  9.31248053e+00, -4.93242440e+01,
       -2.26360423e+01,  2.55794294e+01,  1.95410332e+01, -1.24792965e+00,
       -3.82197716e+01, -9.55591335e+00, -3.46057211e+00,  5.46912242e+01,
       -7.17677478e+00, -2.00378446e+01,  4.72250939e+00, -1.13883302e+01,
        2.79889884e+01, -1.54440088e+00, -3.03929167e+00, -2.24106749e+00,
       -8.66242408e+00,  4.69814012e+00, -2.68467356e+01,  6.76112276e+00,
       -2.32852719e+01,  4.50296452e+01,  2.72562704e+01,  1.50118098e+01,
       -1.02450138e+01, -2.50471602e+01, -2.05599762e+01, -1.35376238e+01,
       -1.14958852e+01, -3.27242450e+01,  7.74935432e+00, -3.68771133e+01,
       -3.68781745e+01, -3.55832684e+01,  5.17891914e+01,  3.61127653e+00,
        4.28144597e+01, -6.59549069e+00,  1.01183062e+00, -4.25198844e+01,
        2.58542564e+01,  2.05684913e+00, -5.77136692e+00,  1.85012097e+01,
       -1.77007304e+00, -3.82178073e+00,  3.12439409e+01, -1.32361673e+01,
       -2.49658041e+01,  2.28632555e+01, -3.30642968e+01, -1.26843702e+00,
       -4.06480440e-01,  5.44528063e+01,  7.14753956e+00,  1.28029830e+01,
        1.35847008e+01,  3.19866616e+00, -2.73036879e+01,  2.16481076e+01,
       -1.89973219e+01, -4.55763866e+01,  2.37400175e+01, -2.58964184e+01,
       -4.35819975e+00, -3.30917124e+01,  2.85579290e+01,  5.38493056e+00,
       -2.15772980e+01,  1.35696581e+01, -4.91227033e+00, -3.41794157e+01,
       -3.11598399e+01, -1.39857979e+01,  1.22003280e+01, -2.83363649e+00,
       -3.03722046e+00, -9.04310784e+00,  6.32523385e+00,  6.33265830e+00,
        3.34404333e+01,  2.36061814e+01,  1.59164560e+01, -1.74407971e+01,
       -2.23041595e+01, -1.84821594e+01, -7.86836858e+00,  1.57790141e+01,
       -4.17792748e+01, -7.39765997e+00,  2.62411712e+01, -3.80903980e+01,
       -4.18976560e+01,  1.05298510e+01,  1.16645300e+01, -8.17613769e+00,
        2.79751521e+01,  2.28474147e+01,  6.49932698e+00,  3.93048199e+01,
       -4.85212442e+01, -3.13213652e+00, -2.25623013e+00, -1.49846159e+00,
       -5.33874457e+00, -2.94900512e+01, -1.21284997e+01,  4.55103277e+01,
        1.07944612e+01,  4.35745573e+00,  6.80093394e+01, -2.36277496e+01,
       -1.38717493e+01,  3.83584244e-01, -7.34892511e+01, -3.99452895e+01,
        2.61627407e+00, -3.27843411e+01, -1.04572527e+01, -2.52378675e+01,
        9.86695795e-01, -2.96467725e+01, -1.62296058e+01,  2.32701891e+01,
        2.87024984e+01,  5.89368770e+01,  9.21830223e-01, -2.02088827e+01,
       -3.72241461e+01,  1.66925422e+01, -2.38216343e+01, -3.69887739e+01,
       -2.49222176e+01,  1.11302166e+01, -5.58114554e+01, -1.39265955e+01,
       -7.71547507e+00,  5.98230532e+00,  3.70262325e+00, -1.53138956e+01,
       -2.26840942e+01, -1.81080327e+01,  1.99161618e+01,  2.70472526e+01,
        1.46381230e+00, -4.19036889e+01,  3.91845132e+00,  1.82293163e+01,
        7.03740628e+00, -2.11061223e+01,  2.53114561e+01, -5.75792057e+01,
       -4.62241737e+01, -1.80917680e+01,  2.50582920e+01,  1.48145046e+01,
        3.59587687e+00,  2.53065479e+01,  3.37236409e+01, -2.96452693e+01,
       -2.63093603e+01, -3.04788397e+00, -1.45319842e+01, -3.43935718e+01,
        4.26228370e+01, -4.55078971e+01, -4.04316274e+01, -6.05082087e+00,
        3.97199156e+01, -1.21704978e+01,  1.81087571e+01, -4.40223265e-01,
        3.97199342e+01,  7.73952026e+00, -2.41962525e+01, -2.63157921e+01,
        4.33176540e+01, -2.45222920e+01,  1.08367074e+01,  1.29266093e+01])

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [ ]:
base_model=DecisionTreeRegressor(max_depth=1)
modelr=AdaBoostRegressor(estimator=base_model,n_estimators=200,random_state=42)
modelr.fit(x_train,y_train)

AdaBoostRegressor(estimator=DecisionTreeRegressor(max_depth=1),
                  n_estimators=200, random_state=42)

In [ ]:
ypredr=modelr.predict(x_test)

In [ ]:
print("trining efficiency",modelr.score(x_train,y_train))
print("testing efficiency",modelr.score(x_test,y_test))

trining efficiency 0.7579278929805958
testing efficiency 0.7425294920959715

In [ ]:
# print("R2 score",r2_score(ytest, ypredr))
# print("MAE",mean_absolute_error(ytest, ypredr))
print("R2 score",r2_score(y_test, ypredr))
print("MAE",mean_absolute_error(y_test, ypredr))

R2 score 0.7425294920959715
MAE 10.31871885643376

# Gradient Boosting

# Gradient Boosting Regressor

In [ ]:
import pandas as pd
import numpy as np
from sklearn.ensemble import GradientBoostingClassifier,GradientBoostingRegressor
from sklearn.tree import DecisionTreeClassifier,DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,f1_score,recall_score,r2_score,mean_absolute_error

In [ ]:
df=pd.read_csv("/content/house_price_regression_dataset.csv")
df

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality,House_Price
0,1360,2,1,1981,0.599637,0,5,2.623829e+05
1,4272,3,3,2016,4.753014,1,6,9.852609e+05
2,3592,1,2,2016,3.634823,0,9,7.779774e+05
3,966,1,2,1977,2.730667,1,8,2.296989e+05
4,4926,2,1,1993,4.699073,0,8,1.041741e+06
...,...,...,...,...,...,...,...,...
995,3261,4,1,1978,2.165110,2,10,7.014940e+05
996,3179,1,2,1999,2.977123,1,10,6.837232e+05
997,2606,4,2,1962,4.055067,0,2,5.720240e+05
998,4723,5,2,1950,1.930921,0,7,9.648653e+05
999,3268,4,2,1983,3.108790,2,2,7.425993e+05

In [ ]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]
x

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality
0,1360,2,1,1981,0.599637,0,5
1,4272,3,3,2016,4.753014,1,6
2,3592,1,2,2016,3.634823,0,9
3,966,1,2,1977,2.730667,1,8
4,4926,2,1,1993,4.699073,0,8
...,...,...,...,...,...,...,...
995,3261,4,1,1978,2.165110,2,10
996,3179,1,2,1999,2.977123,1,10
997,2606,4,2,1962,4.055067,0,2
998,4723,5,2,1950,1.930921,0,7
999,3268,4,2,1983,3.108790,2,2

In [ ]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=42)

In [ ]:
modelr=GradientBoostingRegressor(n_estimators=300)
modelr.fit(xtrain,ytrain)

GradientBoostingRegressor(n_estimators=300)

In [ ]:
ypredr=modelr.predict(xtest)

In [ ]:
print("training efficiency :",modelr.score(xtrain,ytrain))
print("testing efficiency :",modelr.score(xtest,ytest))

training efficiency : 0.9995244930475269
testing efficiency : 0.9967855999516105

In [ ]:
print("r2 score",r2_score(ytest,ypredr))
print("MAE",mean_absolute_error(ytest,ypredr))

r2 score 0.9967855999516105
MAE 11570.462760126928

## GradientBoostingClassifier

In [ ]:
df1=pd.read_csv("/content/heart_disease.csv")
df1

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
0,56.0,Male,153.0,155.0,High,Yes,Yes,No,24.991591,Yes,...,No,High,Medium,7.633228,Medium,342.0,NaN,12.969246,12.387250,No
1,69.0,Female,146.0,286.0,High,No,Yes,Yes,25.221799,No,...,No,Medium,High,8.744034,Medium,133.0,157.0,9.355389,19.298875,No
2,46.0,Male,126.0,216.0,Low,No,No,No,29.855447,No,...,Yes,Low,Low,4.440440,Low,393.0,92.0,12.709873,11.230926,No
3,32.0,Female,122.0,293.0,High,Yes,Yes,No,24.130477,Yes,...,Yes,Low,High,5.249405,High,293.0,94.0,12.509046,5.961958,No
4,60.0,Male,166.0,242.0,Low,Yes,Yes,Yes,20.486289,Yes,...,No,Low,High,7.030971,High,263.0,154.0,10.381259,8.153887,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,25.0,Female,136.0,243.0,Medium,Yes,No,No,18.788791,Yes,...,Yes,Medium,High,6.834954,Medium,343.0,133.0,3.588814,19.132004,Yes
9996,38.0,Male,172.0,154.0,Medium,No,No,No,31.856801,Yes,...,Yes,NaN,High,8.247784,Low,377.0,83.0,2.658267,9.715709,Yes
9997,73.0,Male,152.0,201.0,High,Yes,No,Yes,26.899911,No,...,Yes,NaN,Low,4.436762,Low,248.0,88.0,4.408867,9.492429,Yes
9998,23.0,Male,142.0,299.0,Low,Yes,No,Yes,34.964026,Yes,...,Yes,Medium,High,8.526329,Medium,113.0,153.0,7.215634,11.873486,Yes
9999,38.0,Female,128.0,193.0,Medium,Yes,Yes,Yes,25.111295,No,...,Yes,High,Medium,5.659394,High,121.0,149.0,14.387810,6.208531,Yes

In [ ]:
df1.info()
#Heart Disease Status is the output column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Age                   9971 non-null   float64
 1   Gender                9981 non-null   object
 2   Blood Pressure        9981 non-null   float64
 3   Cholesterol Level     9970 non-null   float64
 4   Exercise Habits       9975 non-null   object
 5   Smoking               9975 non-null   object
 6   Family Heart Disease  9979 non-null   object
 7   Diabetes              9970 non-null   object
 8   BMI                   9978 non-null   float64
 9   High Blood Pressure   9974 non-null   object
 10  Low HDL Cholesterol   9975 non-null   object
 11  High LDL Cholesterol  9974 non-null   object
 12  Alcohol Consumption   7414 non-null   object
 13  Stress Level          9978 non-null   object
 14  Sleep Hours           9975 non-null   float64
 15  Sugar Consumption     9970 non-null   object
 16  Triglyceride Level    9974 non-null   float64
 17  Fasting Blood Sugar   9978 non-null   float64
 18  CRP Level             9974 non-null   float64
 19  Homocysteine Level    9980 non-null   float64
 20  Heart Disease Status  10000 non-null  object
dtypes: float64(9), object(12)
memory usage: 1.6+ MB

In [ ]:
df1.isnull().sum() # to know the count of nul value

Age                       29
Gender                    19
Blood Pressure            19
Cholesterol Level         30
Exercise Habits           25
Smoking                   25
Family Heart Disease      21
Diabetes                  30
BMI                       22
High Blood Pressure       26
Low HDL Cholesterol       25
High LDL Cholesterol      26
Alcohol Consumption     2586
Stress Level              22
Sleep Hours               25
Sugar Consumption         30
Triglyceride Level        26
Fasting Blood Sugar       22
CRP Level                 26
Homocysteine Level        20
Heart Disease Status       0
dtype: int64

In [ ]:
df1.duplicated().sum() # to know the count of duplicated value here no duplicate

np.int64(0)

In [ ]:

#droping the rows
# using dropna()
df1.dropna(inplace=True)

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7067 entries, 1 to 9999
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Age                   7067 non-null   float64
 1   Gender                7067 non-null   object
 2   Blood Pressure        7067 non-null   float64
 3   Cholesterol Level     7067 non-null   float64
 4   Exercise Habits       7067 non-null   object
 5   Smoking               7067 non-null   object
 6   Family Heart Disease  7067 non-null   object
 7   Diabetes              7067 non-null   object
 8   BMI                   7067 non-null   float64
 9   High Blood Pressure   7067 non-null   object
 10  Low HDL Cholesterol   7067 non-null   object
 11  High LDL Cholesterol  7067 non-null   object
 12  Alcohol Consumption   7067 non-null   object
 13  Stress Level          7067 non-null   object
 14  Sleep Hours           7067 non-null   float64
 15  Sugar Consumption     7067 non-null   object
 16  Triglyceride Level    7067 non-null   float64
 17  Fasting Blood Sugar   7067 non-null   float64
 18  CRP Level             7067 non-null   float64
 19  Homocysteine Level    7067 non-null   float64
 20  Heart Disease Status  7067 non-null   object
dtypes: float64(9), object(12)
memory usage: 1.2+ MB

In [ ]:
df.isnull().sum()

Square_Footage          0
Num_Bedrooms            0
Num_Bathrooms           0
Year_Built              0
Lot_Size                0
Garage_Size             0
Neighborhood_Quality    0
House_Price             0
dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder
LE=LabelEncoder()
OE=OrdinalEncoder(categories=[["Low","Medium","High"]])

In [ ]:
df1.columns

Index(['Age', 'Gender', 'Blood Pressure', 'Cholesterol Level',
       'Exercise Habits', 'Smoking', 'Family Heart Disease', 'Diabetes', 'BMI',
       'High Blood Pressure', 'Low HDL Cholesterol', 'High LDL Cholesterol',
       'Alcohol Consumption', 'Stress Level', 'Sleep Hours',
       'Sugar Consumption', 'Triglyceride Level', 'Fasting Blood Sugar',
       'CRP Level', 'Homocysteine Level', 'Heart Disease Status'],
      dtype='object')

In [ ]:
for col in df1.columns:
  if df1[col].dtype == object:
    if 'High' in df1[col].unique():
      df1[col]=OE.fit_transform(df1[[col]])
    else:
      df1[col]=LE.fit_transform(df1[[col]])
df1

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
1,69.0,0,146.0,286.0,2.0,0,1,1,25.221799,0,...,0,1.0,2.0,8.744034,1.0,133.0,157.0,9.355389,19.298875,0
2,46.0,1,126.0,216.0,0.0,0,0,0,29.855447,0,...,1,0.0,0.0,4.440440,0.0,393.0,92.0,12.709873,11.230926,0
3,32.0,0,122.0,293.0,2.0,1,1,0,24.130477,1,...,1,0.0,2.0,5.249405,2.0,293.0,94.0,12.509046,5.961958,0
4,60.0,1,166.0,242.0,0.0,1,1,1,20.486289,1,...,0,0.0,2.0,7.030971,2.0,263.0,154.0,10.381259,8.153887,0
5,25.0,1,152.0,257.0,0.0,1,0,0,28.144681,0,...,0,0.0,1.0,5.504876,0.0,126.0,91.0,4.297575,10.815983,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9992,68.0,0,169.0,291.0,1.0,1,0,0,22.839718,0,...,0,1.0,0.0,6.057509,2.0,299.0,142.0,3.321020,11.910244,1
9994,73.0,0,144.0,191.0,1.0,1,1,1,39.459620,0,...,0,1.0,0.0,7.549114,1.0,200.0,88.0,1.154904,8.021732,1
9995,25.0,0,136.0,243.0,1.0,1,0,0,18.788791,1,...,1,1.0,2.0,6.834954,1.0,343.0,133.0,3.588814,19.132004,1
9998,23.0,1,142.0,299.0,0.0,1,0,1,34.964026,1,...,1,1.0,2.0,8.526329,1.0,113.0,153.0,7.215634,11.873486,1
9999,38.0,0,128.0,193.0,1.0,1,1,1,25.111295,0,...,1,2.0,1.0,5.659394,2.0,121.0,149.0,14.387810,6.208531,1

In [ ]:
x=df1.iloc[:,:-1]
y=df1.iloc[:,-1]

In [ ]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler() # Create an instance of StandardScaler
data = scaler.fit_transform(xtrain)
df5=pd.DataFrame(data,columns=x.columns)
df5

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,Low HDL Cholesterol,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level
0,1.239462,-1.015897,-1.476734,0.534330,1.224701,-1.030802,0.999192,1.009344,-0.852451,-1.015075,-1.000404,-0.976420,0.006941,0.005258,1.545955,1.230623,1.589997,-0.290649,-0.392684,1.642103
1,-0.726821,-1.015897,-1.247402,0.442143,-1.233149,0.970119,-1.000809,1.009344,1.352660,0.985149,0.999596,-0.976420,-1.219197,1.243679,1.330777,0.017174,-1.504389,-0.714629,-1.398527,-0.880437
2,-1.273010,0.984352,0.873915,0.949168,-1.233149,0.970119,-1.000809,-0.990742,0.794097,-1.015075,0.999596,-0.976420,1.233080,0.005258,-0.975424,1.230623,0.980322,0.557312,1.027627,0.106965
3,-0.344488,-1.015897,-1.362068,-0.594952,-1.233149,-1.030802,0.999192,1.009344,0.145193,-1.015075,0.999596,-0.976420,1.233080,-1.233163,1.493719,0.017174,0.267118,1.235681,-0.787552,-0.717707
4,-0.126012,-1.015897,0.759249,1.041354,-0.004224,-1.030802,0.999192,1.009344,-0.109310,0.985149,0.999596,1.024149,-1.219197,1.243679,0.327183,1.230623,-1.216807,1.150885,0.709063,0.824396
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4941,0.037845,0.984352,1.045914,-0.525812,-1.233149,0.970119,-1.000809,1.009344,-1.158943,0.985149,0.999596,-0.976420,-1.219197,1.243679,-0.802765,-1.196275,1.221891,0.642108,-0.672789,-0.325180
4942,0.474796,-1.015897,1.217913,1.617518,-0.004224,-1.030802,0.999192,-0.990742,0.154687,0.985149,-1.000404,1.024149,-1.219197,0.005258,1.649939,0.017174,-0.077981,-1.138609,-1.670878,0.189903
4943,-1.436867,-1.015897,-0.272743,1.548378,1.224701,0.970119,0.999192,1.009344,-0.781243,0.985149,0.999596,-0.976420,-1.219197,1.243679,0.562305,1.230623,1.566990,0.048536,0.839439,0.681391
4944,0.638653,0.984352,0.759249,-0.848464,-0.004224,-1.030802,-1.000809,-0.990742,1.203634,0.985149,-1.000404,-0.976420,0.006941,-1.233163,-0.294298,-1.196275,0.508687,-1.562590,-0.107278,0.213598
4945,1.676413,-1.015897,-0.960738,0.880028,-0.004224,0.970119,-1.000809,-0.990742,1.687218,0.985149,0.999596,-0.976420,0.006941,-1.233163,0.273827,1.230623,0.267118,1.193283,-0.840963,1.123839

In [ ]:
modelc=GradientBoostingClassifier(n_estimators=200,learning_rate=0.02)
modelc.fit(xtrain,ytrain)

GradientBoostingClassifier(learning_rate=0.02, n_estimators=200)

In [ ]:
ypredc=modelc.predict(xtest)
ypredc

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
print("trining accuracy",modelc.score(xtrain,ytrain))
print("testing accuracy",modelc.score(xtest,ytest))

trining accuracy 0.8020622725434695
testing accuracy 0.7901933050447902

In [ ]:
print("presicion score",precision_score(ytest,ypredc))
print("recall score",recall_score(ytest,ypredc))

presicion score 0.5
recall score 0.0022471910112359553

## X-G BOOST

# Classifier

In [ ]:
import pandas as pd
from sklearn.datasets import load_iris
from xgboost import XGBClassifier,XGBRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,r2_score

In [ ]:
data=load_iris()
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5.5, 4.2, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.2],
        [5. , 3.2, 1.2, 0.2],
        [5.5, 3.5, 1.3, 0.2],
        [4.9, 3.6, 1.4, 0.1],
        [4.4, 3. , 1.3, 0.2],
        [5.1, 3.4, 1.5, 0.2],
        [5. , 3.5, 1.3, 0.3],
        [4.5, 2.3, 1.3, 0.3],
        [4.4, 3.2, 1.3, 0.2],
        [5. , 3.5, 1.6, 0.6],
        [5.1, 3.8, 1.9, 0.4],
        [4.8, 3. , 1.4, 0.3],
        [5.1, 3.8, 1.6, 0.2],
        [4.6, 3.2, 1.4, 0.2],
        [5.3, 3.7, 1.5, 0.2],
        [5. , 3.3, 1.4, 0.2],
        [7. , 3.2, 4.7, 1.4],
        [6.4, 3.2, 4.5, 1.5],
        [6.9, 3.1, 4.9, 1.5],
        [5.5, 2.3, 4. , 1.3],
        [6.5, 2.8, 4.6, 1.5],
        [5.7, 2.8, 4.5, 1.3],
        [6.3, 3.3, 4.7, 1.6],
        [4.9, 2.4, 3.3, 1. ],
        [6.6, 2.9, 4.6, 1.3],
        [5.2, 2.7, 3.9, 1.4],
        [5. , 2. , 3.5, 1. ],
        [5.9, 3. , 4.2, 1.5],
        [6. , 2.2, 4. , 1. ],
        [6.1, 2.9, 4.7, 1.4],
        [5.6, 2.9, 3.6, 1.3],
        [6.7, 3.1, 4.4, 1.4],
        [5.6, 3. , 4.5, 1.5],
        [5.8, 2.7, 4.1, 1. ],
        [6.2, 2.2, 4.5, 1.5],
        [5.6, 2.5, 3.9, 1.1],
        [5.9, 3.2, 4.8, 1.8],
        [6.1, 2.8, 4. , 1.3],
        [6.3, 2.5, 4.9, 1.5],
        [6.1, 2.8, 4.7, 1.2],
        [6.4, 2.9, 4.3, 1.3],
        [6.6, 3. , 4.4, 1.4],
        [6.8, 2.8, 4.8, 1.4],
        [6.7, 3. , 5. , 1.7],
        [6. , 2.9, 4.5, 1.5],
        [5.7, 2.6, 3.5, 1. ],
        [5.5, 2.4, 3.8, 1.1],
        [5.5, 2.4, 3.7, 1. ],
        [5.8, 2.7, 3.9, 1.2],
        [6. , 2.7, 5.1, 1.6],
        [5.4, 3. , 4.5, 1.5],
        [6. , 3.4, 4.5, 1.6],
        [6.7, 3.1, 4.7, 1.5],
        [6.3, 2.3, 4.4, 1.3],
        [5.6, 3. , 4.1, 1.3],
        [5.5, 2.5, 4. , 1.3],
        [5.5, 2.6, 4.4, 1.2],
        [6.1, 3. , 4.6, 1.4],
        [5.8, 2.6, 4. , 1.2],
        [5. , 2.3, 3.3, 1. ],
        [5.6, 2.7, 4.2, 1.3],
        [5.7, 3. , 4.2, 1.2],
        [5.7, 2.9, 4.2, 1.3],
        [6.2, 2.9, 4.3, 1.3],
        [5.1, 2.5, 3. , 1.1],
        [5.7, 2.8, 4.1, 1.3],
        [6.3, 3.3, 6. , 2.5],
        [5.8, 2.7, 5.1, 1.9],
        [7.1, 3. , 5.9, 2.1],
        [6.3, 2.9, 5.6, 1.8],
        [6.5, 3. , 5.8, 2.2],
        [7.6, 3. , 6.6, 2.1],
        [4.9, 2.5, 4.5, 1.7],
        [7.3, 2.9, 6.3, 1.8],
        [6.7, 2.5, 5.8, 1.8],
        [7.2, 3.6, 6.1, 2.5],
        [6.5, 3.2, 5.1, 2. ],
        [6.4, 2.7, 5.3, 1.9],
        [6.8, 3. , 5.5, 2.1],
        [5.7, 2.5, 5. , 2. ],
        [5.8, 2.8, 5.1, 2.4],
        [6.4, 3.2, 5.3, 2.3],
        [6.5, 3. , 5.5, 1.8],
        [7.7, 3.8, 6.7, 2.2],
        [7.7, 2.6, 6.9, 2.3],
        [6. , 2.2, 5. , 1.5],
        [6.9, 3.2, 5.7, 2.3],
        [5.6, 2.8, 4.9, 2. ],
        [7.7, 2.8, 6.7, 2. ],
        [6.3, 2.7, 4.9, 1.8],
        [6.7, 3.3, 5.7, 2.1],
        [7.2, 3.2, 6. , 1.8],
        [6.2, 2.8, 4.8, 1.8],
        [6.1, 3. , 4.9, 1.8],
        [6.4, 2.8, 5.6, 2.1],
        [7.2, 3. , 5.8, 1.6],
        [7.4, 2.8, 6.1, 1.9],
        [7.9, 3.8, 6.4, 2. ],
        [6.4, 2.8, 5.6, 2.2],
        [6.3, 2.8, 5.1, 1.5],
        [6.1, 2.6, 5.6, 1.4],
        [7.7, 3. , 6.1, 2.3],
        [6.3, 3.4, 5.6, 2.4],
        [6.4, 3.1, 5.5, 1.8],
        [6. , 3. , 4.8, 1.8],
        [6.9, 3.1, 5.4, 2.1],
        [6.7, 3.1, 5.6, 2.4],
        [6.9, 3.1, 5.1, 2.3],
        [5.8, 2.7, 5.1, 1.9],
        [6.8, 3.2, 5.9, 2.3],
        [6.7, 3.3, 5.7, 2.5],
        [6.7, 3. , 5.2, 2.3],
        [6.3, 2.5, 5. , 1.9],
        [6.5, 3. , 5.2, 2. ],
        [6.2, 3.4, 5.4, 2.3],
        [5.9, 3. , 5.1, 1.8]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 'frame': None,
 'target_names': array(['setosa', 'versicolor', 'virginica'], dtype='<U10'),
 'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 150 (50 in each of three classes)\n:Number of Attributes: 4 numeric, predictive attributes and the class\n:Attribute Information:\n    - sepal length in cm\n    - sepal width in cm\n    - petal length in cm\n    - petal width in cm\n    - class:\n            - Iris-Setosa\n            - Iris-Versicolour\n            - Iris-Virginica\n\n:Summary Statistics:\n\n============== ==== ==== ======= ===== ====================\n                Min  Max   Mean    SD   Class Correlation\n============== ==== ==== ======= ===== ====================\nsepal length:   4.3  7.9   5.84   0.83    0.7826\nsepal width:    2.0  4.4   3.05   0.43   -0.4194\npetal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\npetal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n============== ==== ==== ======= ===== ====================\n\n:Missing Attribute Values: None\n:Class Distribution: 33.3% for each of 3 classes.\n:Creator: R.A. Fisher\n:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)\n:Date: July, 1988\n\nThe famous Iris database, first used by Sir R.A. Fisher. The dataset is taken\nfrom Fisher\'s paper. Note that it\'s the same as in R, but not as in the UCI\nMachine Learning Repository, which has two wrong data points.\n\nThis is perhaps the best known database to be found in the\npattern recognition literature.  Fisher\'s paper is a classic in the field and\nis referenced frequently to this day.  (See Duda & Hart, for example.)  The\ndata set contains 3 classes of 50 instances each, where each class refers to a\ntype of iris plant.  One class is linearly separable from the other 2; the\nlatter are NOT linearly separable from each other.\n\n.. dropdown:: References\n\n  - Fisher, R.A. "The use of multiple measurements in taxonomic problems"\n    Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to\n    Mathematical Statistics" (John Wiley, NY, 1950).\n  - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.\n    (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.\n  - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System\n    Structure and Classification Rule for Recognition in Partially Exposed\n    Environments".  IEEE Transactions on Pattern Analysis and Machine\n    Intelligence, Vol. PAMI-2, No. 1, 67-71.\n  - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions\n    on Information Theory, May 1972, 431-433.\n  - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II\n    conceptual clustering system finds 3 classes in the data.\n  - Many, many more ...\n',
 'feature_names': ['sepal length (cm)',
  'sepal width (cm)',
  'petal length (cm)',
  'petal width (cm)'],
 'filename': 'iris.csv',
 'data_module': 'sklearn.datasets.data'}

In [ ]:
df=pd.DataFrame(data.data,columns=data.feature_names)
df['target']=data.target
df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [ ]:
x=df.drop('target',axis=1)
y=df.target

In [ ]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=42)

In [ ]:
modelc=XGBClassifier(n_estimators=100,learning_rate=0.01,max_depth=5,random_state=42)
modelc.fit(xtrain,ytrain)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.01, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=100,
              n_jobs=None, num_parallel_tree=None, ...)

In [ ]:
ypredc=modelc.predict(xtest)
ypredc

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0])

In [ ]:
print("trining accuracy",modelc.score(xtrain,ytrain))
print("testing accuracy",modelc.score(xtest,ytest))

trining accuracy 0.9714285714285714
testing accuracy 1.0

In [ ]:
print("accuracy score",accuracy_score(ytest,ypredc))

accuracy score 1.0

# Regressor

In [ ]:
df1=pd.read_csv(" https://raw.githubusercontent.com/Jeevita-R/ML_datasets/refs/heads/main/Fetch_california_housing.csv")
df1

,Unnamed: 0,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,target
0,0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...,...
20635,20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

In [ ]:
df=df1.drop("Unnamed: 0", axis=1)
df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,target
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

In [ ]:
x=df.drop('target',axis=1)
y=df.target
x

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25
...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24

In [ ]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler() # Create an instance of StandardScaler
xtrain_scaled = scaler.fit_transform(xtrain)
xtest_scaled = scaler.transform(xtest) # Correctly transform xtest
df5 = pd.DataFrame(xtrain_scaled, columns=x.columns) # Use xtrain_scaled
df5

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,0.133506,0.509357,0.181060,-0.273850,-0.184117,-0.010825,-0.805682,0.780934
1,-0.532218,-0.679873,-0.422630,-0.047868,-0.376191,-0.089316,-1.339473,1.245270
2,0.170990,-0.362745,0.073128,-0.242600,-0.611240,-0.044800,-0.496645,-0.277552
3,-0.402916,-1.155565,0.175848,-0.008560,-0.987495,-0.075230,1.690024,-0.706938
4,-0.299285,1.857152,-0.259598,-0.070993,0.086015,-0.066357,0.992350,-1.430902
...,...,...,...,...,...,...,...,...
14443,1.308827,0.509357,0.281603,-0.383849,-0.675265,-0.007030,-0.875918,0.810891
14444,-0.434100,0.350793,0.583037,0.383154,0.285105,0.063443,-0.763541,1.075513
14445,-0.494787,0.588640,-0.591570,-0.040978,0.287736,0.017201,-0.758858,0.601191
14446,0.967171,-1.076283,0.390149,-0.067164,0.306154,0.004821,0.903385,-1.186252
14447,-0.683202,1.857152,-0.829656,-0.087729,1.044630,-0.081672,0.992350,-1.415923

In [ ]:
modelr=XGBRegressor(n_estimators=400,learning_rate=0.01,max_depth=10,random_state=42)
modelr.fit(xtrain,ytrain)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.01, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=10,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=400,
             n_jobs=None, num_parallel_tree=None, ...)

In [ ]:
ypredr=modelr.predict(xtest)
ypredr

array([0.53363776, 0.797851  , 4.8694043 , ..., 2.4090693 , 1.4668664 ,
       2.1262255 ], dtype=float32)

In [ ]:
print("trining accuracy",modelr.score(xtrain,ytrain))
print("testing accuracy",modelr.score(xtest,ytest))
print("r2 score",r2_score(ytest,ypredr))

trining accuracy 0.9559793816980929
testing accuracy 0.8200826351787331
r2 score 0.8200826351787331